branches:
  except:
    - gh-pages

language: cpp

compiler:
  - clang
  - gcc

git:
  submodules: false

env:
  global:
    - NUPIC=$TRAVIS_BUILD_DIR
    - NTA=$HOME/nta/eng
    - PATH=$TRAVIS_BUILD_DIR/python/bin:$PATH
  matrix:
    - PY_VER=2.7
    - PY_VER=2.6

notifications:
  irc:
    channels:
      - "irc.freenode.net#nupic-hackers"
  webhooks: http://issues.numenta.org:8081/travis

before_install:
  # Due to recent changes to Travis-CI build environment, we need to download,
  # build, and install, python, setuptools, pip, and all of the nupic python
  # dependencies
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install libbz2-dev zlib1g-dev libssl-dev libsasl2-dev libreadline-dev python$PY_VER python$PY_VER-dev
  #- (wget https://www.python.org/ftp/python/$PY_VER_FULL/Python-$PY_VER_FULL.tgz && tar xzf Python-$PY_VER_FULL.tgz && cd Python-$PY_VER_FULL && ./configure --enable-shared --prefix=${TRAVIS_BUILD_DIR}/python && make && make altinstall)

install:
  # Prefix env with our own python installation
  - mkdir -p $TRAVIS_BUILD_DIR/python/bin
  - mkdir -p $TRAVIS_BUILD_DIR/python/lib/python$PY_VER/site-packages
  - "export PATH=$TRAVIS_BUILD_DIR/python/bin:$PATH"
  - "export PYTHONPATH=$TRAVIS_BUILD_DIR/python/lib/python$PY_VER/site-packages:$PYTHONPATH:$NTA/lib/python$PY_VER/site-packages"
  - "export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/python/lib:$LD_LIBRARY_PATH"
  #- "ln -s $TRAVIS_BUILD_DIR/python/bin/python$PY_VER_SHORT $TRAVIS_BUILD_DIR/python/bin/python"
  # Workaround for multiprocessing.Queue SemLock error from run_opf_bechmarks_test.
  # See: https://github.com/travis-ci/travis-cookbooks/issues/155
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - which python$PY_VER
  - python$PY_VER --version
  # Install setuptools + pip
  - wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py -O - | python$PY_VER
  # - (wget https://pypi.python.org/packages/source/s/setuptools/setuptools-3.4.4.tar.gz && tar xzvf setuptools-3.4.4.tar.gz && cd setuptools-3.4.4 && python setup.py install --prefix=$TRAVIS_BUILD_DIR/python)
  # - easy_install --install-dir=$TRAVIS_BUILD_DIR/python/lib/python$PY_VER_SHORT/site-packages --script-dir=$TRAVIS_BUILD_DIR/python/bin pip
  # Install NuPIC python dependencies
  - easy_install-$PY_VER --install-dir=$TRAVIS_BUILD_DIR/python/lib/python$PY_VER/site-packages --script-dir=$TRAVIS_BUILD_DIR/python/bin virtualenv
  - virtualenv-$PY_VER --python=$TRAVIS_BUILD_DIR/python/bin/python .
  - source bin/activate
  - pip-$PY_VER install -q -r $NUPIC/external/common/requirements.txt --install-option="--prefix=$TRAVIS_BUILD_DIR/python"
  - "mkdir -p $TRAVIS_BUILD_DIR/build/scripts"
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  - "cmake --version"
  # Build NuPIC
  - "PYTHON=`which python$PY_VER` cmake $NUPIC -DPROJECT_BUILD_RELEASE_DIR:STRING=$NTA"
  - "make -j3"
  - "cd"

script:
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  # legacy binary tests
  - "make tests_pyhtm"
  # actual unit tests
  - "make tests_run_all"
  - "cd"

  # run all example files
    # examples/bindings
  - "python$PY_VER $NUPIC/examples/bindings/sparse_matrix_how_to.py"
##  - "python $NUPIC/examples/bindings/svm_how_to.py" # tkinter missing in Travis build machine
##  - "python $NUPIC/examples/bindings/temporal_pooler_how_to.py" # tkinter too
    # examples/opf (run atleast 1 from each category)
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/anomaly/spatial/2field_few_skewed/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/anomaly/temporal/saw_200/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/classification/category_TP_1/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/missing_record/simple_0/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/multistep/hotgym/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/opfrunexperiment_test/simpleOPF/hotgym_1hr_agg/"
             # opf/experiments/params - skip now
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/spatial_classification/category_1/"
    # examples/prediction
  - "python$PY_VER $NUPIC/examples/prediction/RunExperiment.py $NUPIC/examples/prediction/experiments/dutyCycle/problem/"
    # examples/tp
  - "python$PY_VER $NUPIC/examples/tp/hello_tp.py"
  - "python$PY_VER $NUPIC/examples/tp/tp_test.py"

